services:
  freshrss:
    image: freshrss/freshrss
    container_name: ct-freshrss
    hostname: ct-freshrss
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Paris
    ports:
      - "3001:80"
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    restart: unless-stopped

volumes:
  freshrss-data:
  freshrss-extensions:
