services:
  freshrss:
    image: freshrss/freshrss
    container_name: ct-freshrss
    hostname: ct-freshrss
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/Paris
    volumes:
      - freshrss-data:/var/www/FreshRSS/data
      - freshrss-extensions:/var/www/FreshRSS/extensions
    restart: unless-stopped
    networks:
      - web
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.vault.rule=Host(`host.fr`)"
    - "traefik.http.routers.vault.entrypoints=websecure"

volumes:
  freshrss-data:
  freshrss-extensions:
networks:
  web:
    external:
      true